name: 'Setup Repo'
description: 'Sets up Bun, restores caches, and installs dependencies'

inputs:
  bun-version:
    description: 'Version of Bun to use'
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Cache Bun Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: ${{ runner.os }}-bun-

    - name: Install Dependencies
      shell: bash
      run: bun install --frozen-lockfile

    - name: Cache Moon Artifacts
      uses: actions/cache@v4
      with:
        path: |
          .moon/cache/hashes
          .moon/cache/outputs
        key: ${{ runner.os }}-moon-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-moon-
