/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UhOhRouteImport } from './routes/uh-oh'
import { Route as WelcomeRouteRouteImport } from './routes/welcome/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appTransactionsRouteRouteImport } from './routes/(app)/transactions/route'
import { Route as appSettingsRouteRouteImport } from './routes/(app)/settings/route'
import { Route as appOverviewRouteRouteImport } from './routes/(app)/overview/route'
import { Route as appsuRouteRouteImport } from './routes/(app)/(su)/route'
import { Route as TransactionReceiptTransactionIdRouteImport } from './routes/transaction/receipt/$transactionId'
import { Route as ApiEghlReturnRouteImport } from './routes/api/eghl.return'
import { Route as ApiEghlCronRouteImport } from './routes/api/eghl.cron'
import { Route as ApiEghlCallbackRouteImport } from './routes/api/eghl.callback'
import { Route as authWelcomeSignupRouteImport } from './routes/(auth)/welcome.signup'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/auth.login'
import { Route as appTransactionTransactionIdRouteImport } from './routes/(app)/transaction/$transactionId'
import { Route as appsuReportsRouteRouteImport } from './routes/(app)/(su)/reports/route'
import { Route as appsuInsightsRouteRouteImport } from './routes/(app)/(su)/insights/route'

const UhOhRoute = UhOhRouteImport.update({
  id: '/uh-oh',
  path: '/uh-oh',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRouteRoute = WelcomeRouteRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appTransactionsRouteRoute = appTransactionsRouteRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRouteRoute = appSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appOverviewRouteRoute = appOverviewRouteRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => appRouteRoute,
} as any)
const appsuRouteRoute = appsuRouteRouteImport.update({
  id: '/(su)',
  getParentRoute: () => appRouteRoute,
} as any)
const TransactionReceiptTransactionIdRoute =
  TransactionReceiptTransactionIdRouteImport.update({
    id: '/transaction/receipt/$transactionId',
    path: '/transaction/receipt/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEghlReturnRoute = ApiEghlReturnRouteImport.update({
  id: '/api/eghl/return',
  path: '/api/eghl/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEghlCronRoute = ApiEghlCronRouteImport.update({
  id: '/api/eghl/cron',
  path: '/api/eghl/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEghlCallbackRoute = ApiEghlCallbackRouteImport.update({
  id: '/api/eghl/callback',
  path: '/api/eghl/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const authWelcomeSignupRoute = authWelcomeSignupRouteImport.update({
  id: '/welcome/signup',
  path: '/welcome/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => authRouteRoute,
} as any)
const appTransactionTransactionIdRoute =
  appTransactionTransactionIdRouteImport.update({
    id: '/transaction/$transactionId',
    path: '/transaction/$transactionId',
    getParentRoute: () => appRouteRoute,
  } as any)
const appsuReportsRouteRoute = appsuReportsRouteRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => appsuRouteRoute,
} as any)
const appsuInsightsRouteRoute = appsuInsightsRouteRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => appsuRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRouteRoute
  '/uh-oh': typeof UhOhRoute
  '/overview': typeof appOverviewRouteRoute
  '/settings': typeof appSettingsRouteRoute
  '/transactions': typeof appTransactionsRouteRoute
  '/insights': typeof appsuInsightsRouteRoute
  '/reports': typeof appsuReportsRouteRoute
  '/transaction/$transactionId': typeof appTransactionTransactionIdRoute
  '/auth/login': typeof authAuthLoginRoute
  '/welcome/signup': typeof authWelcomeSignupRoute
  '/api/eghl/callback': typeof ApiEghlCallbackRoute
  '/api/eghl/cron': typeof ApiEghlCronRoute
  '/api/eghl/return': typeof ApiEghlReturnRoute
  '/transaction/receipt/$transactionId': typeof TransactionReceiptTransactionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRouteRoute
  '/uh-oh': typeof UhOhRoute
  '/overview': typeof appOverviewRouteRoute
  '/settings': typeof appSettingsRouteRoute
  '/transactions': typeof appTransactionsRouteRoute
  '/insights': typeof appsuInsightsRouteRoute
  '/reports': typeof appsuReportsRouteRoute
  '/transaction/$transactionId': typeof appTransactionTransactionIdRoute
  '/auth/login': typeof authAuthLoginRoute
  '/welcome/signup': typeof authWelcomeSignupRoute
  '/api/eghl/callback': typeof ApiEghlCallbackRoute
  '/api/eghl/cron': typeof ApiEghlCronRoute
  '/api/eghl/return': typeof ApiEghlReturnRoute
  '/transaction/receipt/$transactionId': typeof TransactionReceiptTransactionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/welcome': typeof WelcomeRouteRoute
  '/uh-oh': typeof UhOhRoute
  '/(app)/(su)': typeof appsuRouteRouteWithChildren
  '/(app)/overview': typeof appOverviewRouteRoute
  '/(app)/settings': typeof appSettingsRouteRoute
  '/(app)/transactions': typeof appTransactionsRouteRoute
  '/(app)/(su)/insights': typeof appsuInsightsRouteRoute
  '/(app)/(su)/reports': typeof appsuReportsRouteRoute
  '/(app)/transaction/$transactionId': typeof appTransactionTransactionIdRoute
  '/(auth)/auth/login': typeof authAuthLoginRoute
  '/(auth)/welcome/signup': typeof authWelcomeSignupRoute
  '/api/eghl/callback': typeof ApiEghlCallbackRoute
  '/api/eghl/cron': typeof ApiEghlCronRoute
  '/api/eghl/return': typeof ApiEghlReturnRoute
  '/transaction/receipt/$transactionId': typeof TransactionReceiptTransactionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/uh-oh'
    | '/overview'
    | '/settings'
    | '/transactions'
    | '/insights'
    | '/reports'
    | '/transaction/$transactionId'
    | '/auth/login'
    | '/welcome/signup'
    | '/api/eghl/callback'
    | '/api/eghl/cron'
    | '/api/eghl/return'
    | '/transaction/receipt/$transactionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/uh-oh'
    | '/overview'
    | '/settings'
    | '/transactions'
    | '/insights'
    | '/reports'
    | '/transaction/$transactionId'
    | '/auth/login'
    | '/welcome/signup'
    | '/api/eghl/callback'
    | '/api/eghl/cron'
    | '/api/eghl/return'
    | '/transaction/receipt/$transactionId'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/welcome'
    | '/uh-oh'
    | '/(app)/(su)'
    | '/(app)/overview'
    | '/(app)/settings'
    | '/(app)/transactions'
    | '/(app)/(su)/insights'
    | '/(app)/(su)/reports'
    | '/(app)/transaction/$transactionId'
    | '/(auth)/auth/login'
    | '/(auth)/welcome/signup'
    | '/api/eghl/callback'
    | '/api/eghl/cron'
    | '/api/eghl/return'
    | '/transaction/receipt/$transactionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  WelcomeRouteRoute: typeof WelcomeRouteRoute
  UhOhRoute: typeof UhOhRoute
  ApiEghlCallbackRoute: typeof ApiEghlCallbackRoute
  ApiEghlCronRoute: typeof ApiEghlCronRoute
  ApiEghlReturnRoute: typeof ApiEghlReturnRoute
  TransactionReceiptTransactionIdRoute: typeof TransactionReceiptTransactionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uh-oh': {
      id: '/uh-oh'
      path: '/uh-oh'
      fullPath: '/uh-oh'
      preLoaderRoute: typeof UhOhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/transactions': {
      id: '/(app)/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof appTransactionsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/overview': {
      id: '/(app)/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof appOverviewRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(su)': {
      id: '/(app)/(su)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appsuRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/transaction/receipt/$transactionId': {
      id: '/transaction/receipt/$transactionId'
      path: '/transaction/receipt/$transactionId'
      fullPath: '/transaction/receipt/$transactionId'
      preLoaderRoute: typeof TransactionReceiptTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eghl/return': {
      id: '/api/eghl/return'
      path: '/api/eghl/return'
      fullPath: '/api/eghl/return'
      preLoaderRoute: typeof ApiEghlReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eghl/cron': {
      id: '/api/eghl/cron'
      path: '/api/eghl/cron'
      fullPath: '/api/eghl/cron'
      preLoaderRoute: typeof ApiEghlCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eghl/callback': {
      id: '/api/eghl/callback'
      path: '/api/eghl/callback'
      fullPath: '/api/eghl/callback'
      preLoaderRoute: typeof ApiEghlCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/welcome/signup': {
      id: '/(auth)/welcome/signup'
      path: '/welcome/signup'
      fullPath: '/welcome/signup'
      preLoaderRoute: typeof authWelcomeSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/auth/login': {
      id: '/(auth)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/transaction/$transactionId': {
      id: '/(app)/transaction/$transactionId'
      path: '/transaction/$transactionId'
      fullPath: '/transaction/$transactionId'
      preLoaderRoute: typeof appTransactionTransactionIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(su)/reports': {
      id: '/(app)/(su)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof appsuReportsRouteRouteImport
      parentRoute: typeof appsuRouteRoute
    }
    '/(app)/(su)/insights': {
      id: '/(app)/(su)/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof appsuInsightsRouteRouteImport
      parentRoute: typeof appsuRouteRoute
    }
  }
}

interface appsuRouteRouteChildren {
  appsuInsightsRouteRoute: typeof appsuInsightsRouteRoute
  appsuReportsRouteRoute: typeof appsuReportsRouteRoute
}

const appsuRouteRouteChildren: appsuRouteRouteChildren = {
  appsuInsightsRouteRoute: appsuInsightsRouteRoute,
  appsuReportsRouteRoute: appsuReportsRouteRoute,
}

const appsuRouteRouteWithChildren = appsuRouteRoute._addFileChildren(
  appsuRouteRouteChildren,
)

interface appRouteRouteChildren {
  appsuRouteRoute: typeof appsuRouteRouteWithChildren
  appOverviewRouteRoute: typeof appOverviewRouteRoute
  appSettingsRouteRoute: typeof appSettingsRouteRoute
  appTransactionsRouteRoute: typeof appTransactionsRouteRoute
  appTransactionTransactionIdRoute: typeof appTransactionTransactionIdRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appsuRouteRoute: appsuRouteRouteWithChildren,
  appOverviewRouteRoute: appOverviewRouteRoute,
  appSettingsRouteRoute: appSettingsRouteRoute,
  appTransactionsRouteRoute: appTransactionsRouteRoute,
  appTransactionTransactionIdRoute: appTransactionTransactionIdRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authAuthLoginRoute: typeof authAuthLoginRoute
  authWelcomeSignupRoute: typeof authWelcomeSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAuthLoginRoute: authAuthLoginRoute,
  authWelcomeSignupRoute: authWelcomeSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  WelcomeRouteRoute: WelcomeRouteRoute,
  UhOhRoute: UhOhRoute,
  ApiEghlCallbackRoute: ApiEghlCallbackRoute,
  ApiEghlCronRoute: ApiEghlCronRoute,
  ApiEghlReturnRoute: ApiEghlReturnRoute,
  TransactionReceiptTransactionIdRoute: TransactionReceiptTransactionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './entry-start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
